### PR TITLE
dotnet web api endpoints solution

### PR DESCRIPTION
**Pull request by gpierrick**

### CODE REVIEW

**Comment by jexp** [comment]
Thanks a lot @gpierrick 
Could please you move it into a `neo4jclient` subdirectory? And add a readme.adoc with explanations / instructions on setup and running and (later Azure deployment)?

**Comment by gpierrick** [comment]
Sure thing

**Comment by gpierrick** [comment]
@jexp done!

**Comment by jexp** [comment]
Amazing, thanks !

**Pull request merged**
