### PR TITLE
Remove part about squashing commits

### PR DESCRIPTION
**Pull request by Mats-SX**
Also adds a link to a great read on commit messages.

### CODE REVIEW

**Comment by whatSocks** [comment]
Why remove the part about squashing commits?

**Comment by Mats-SX** [comment]
@whatSocks Because the neo4j devteam does not work like that, and it goes against well-known best practices for software development in general. See for example here: http://www.git-tower.com/learn/git/ebook/command-line/appendix/best-practices

> Commit Often
> 
> Committing often keeps your commits small and, again, helps you commit only related changes. Moreover, it allows you to share your code more frequently with others. That way it’s easier for everyone to integrate changes regularly and avoid having merge conflicts. Having few large commits and sharing them rarely, in contrast, makes it hard both to solve conflicts and to comprehend what happened.

**Comment by craigtaverner** [comment]
I know I have asked people to split up commits on occasion, especially when the work they were doing naturally lead to some refactoring or cleanup, and having the cleanup in the same commit as the actual work made it harder to review. I think the only real rule is that you want to make sure your commits make sense, sometimes merging commits to remove some incorrect work you want to dispose of, and sometimes splitting up to increase clarify of code reviews. I do think the second on merging commits did have some nice technical advice on how to merge them in the (hopefully rare) cases you do want to do this. But I see the point that removing that second does better align with what we think is more common practice.

**Comment by Mats-SX** [comment]
I think we shouldn't give too hard rules on how contributors should structure their PRs. Common sense and good practice should be enough, and my change does link to a resource for the latter at least.

But telling people to squash it all to one commit is not what we want to do.

**Comment by jexp** [comment]
merged manually

**Comment by Mats-SX** [comment]
@jexp Thank you.

**Pull request closed without merging**
